kind: pipeline
type: docker      # 在 Docker 內部執行管道命令
name: test       # 可自行定義的名稱

steps:
  - name: tag-docker-image
    image: alpine
    commands:
    - echo -n "$(date +'%Y-%m-%d_%H-%M')_${DRONE_COMMIT}, latest" > .tags

  - name: build-docker-image
    image: plugins/docker
    settings:
      repo: host.docker.internal:80/test/drone_test
      registry: host.docker.internal:80
      username: admin
      password: Harbor12345
      insecure: true
